defaults:
  - base_BOND_model_config


model_type: "bert"
term_dropout_ratio: 0.05
model_name_or_path: "dmis-lab/biobert-base-cased-v1.1"
learning_rate: 1e-5
weight_decay: 1e-4
adam_epsilon: 1e-8
adam_beta1: 0.9
adam_beta2: 0.98
num_train_epochs: 10
per_gpu_train_batch_size: 64
per_gpu_eval_batch_size: 64
logging_steps: 100
save_steps: 2700
do_train: False
do_eval: True
do_predict: True
evaluate_during_training: True
seed: 0
max_length: 128
overwrite_output_dir: True
self_training_reinit: 0
self_training_begin_step: 680
self_training_label_mode: soft
self_training_period: 6
# "178",
self_training_hp_label: 5.9
pad_to_max_length: True